### ISSUE TITLE
Bootstrap NPM dependency error

### ISSUE THREAD

**Issue by georgeweiler** [MichaelDurfey/WeatherApp#1]
<img width="837" alt="screen shot 2017-03-21 at 1 33 59 pm" src="https://cloud.githubusercontent.com/assets/15269424/24169508/153ae8b8-0e3b-11e7-86be-2de7951ea0fc.png">

NPM throws an error related to the bootstrap version you're referencing.

**Comment by MichaelDurfey** [comment]
I’ll update the dependency.. think i messed it up with the 4.0.0 version.. that isn’t even out yet I think


Michael Durfey
t:   858-336-0794
e:  mdurfey@me.com

**Comment by MichaelDurfey** [comment]
I updated the package dependencies with a current version of bootstrap "^3.3.7"
